### ISSUE TITLE
Light Calibration Code

### ISSUE THREAD

**Issue by drewsed** [yqueau/microgeometry_ps#1]
Hi yqueau,

thank you so much for uploading the code of this outstanding work. I'm new to PS and machine vision, but with your code and papers i could reproduce your scenarios pretty well for my first try.

According to the paper you use a Dome Light Scene for illumination. Do you also have light calibration code for this illumination scene? I ask just because i do not want to re-invent the wheel :)

Thanks in advance!

Greetings,
drewsed

**Comment by yqueau** [comment]
Hi Drewsed,

Sorry, the microgeometry stuff is part of a project with a company, and the
light calibration part for this one is protected and cannot be shared :/

Best,
Yvain

2017-11-30 10:56 GMT+01:00 drewsed <notifications@github.com>:

**Comment by drewsed** [comment]
Hi Yvain,

thanks for the response, i suspected something like this while reading about the partner company in the paper.

Regards,
drewsed
